### ISSUE TITLE
Browser error: unexpected token ‘<’

### ISSUE THREAD

**Issue by beebox** [themefisher/kross-hugo-portfolio-template#5]
Hi,

I'm using the Kross Hugo theme and experiencing an error.  I can reproduce the error by creating a new hugo project, adding kross hugo as a submodule, and setting the theme in config.toml
```
theme = "kross-hugo"
```

Chrome and Safari show the error Unexpected token: < in line one of Index which is

Looking around in chrome dev tools, it appears 2 index pages are loaded, (index) page is listed twice in the Sources panel. I’m guessing the error occurs when the browser sees a second doctype.
<img width="576" alt="Hugo unexpected token new site" src="https://user-images.githubusercontent.com/597855/68184858-086a5480-ff55-11e9-95ec-57852bdc99d5.png">
Any suggestion on how to troubleshoot this problem?

Thank you

**Comment by beebox** [comment]
I created a new site and found the issue started after adding the kross-hugo theme.  After a bit of troubleshooting, I found this code in the footer partial was causing the issue.

```
{{ "<!-- Google Map API -->" | safeHTML }}
<script src="{{ .Site.Params.gmapAPI | absURL }}"></script> 
```

I think the problem was due to the variable .Site.Params.gmapAPI not being set and the pipe to absURL generating "http://localhost:1313/" as the script source.

**Comment by Somrat37** [comment]
hey @beebox ,

Thanks for your concern, just remove this line from footer, or pull the latest code.

**Comment by beebox** [comment]
thanks @Somrat37
