### ISSUE TITLE
Wrong type of pages listed in Blog section of Homepage

### ISSUE THREAD

**Issue by Bartojan** [themefisher/kross-hugo-portfolio-template#6]
https://github.com/themefisher/kross-hugo-portfolio-template/blob/effec3593d2d8bef21c8fe906f221b3845666702/layouts/index.html#L255
In the Blog section on Homepage there are listed 3 newest pages of ANY type, but there should be only pages of type Blog.

**Comment by Somrat37** [comment]
@Bartojan 

thanks for your concern, this issue has been fixed, please pull the latest code.

**Comment by ericlentz** [comment]
The fix isn't quite enough. Adding another section, for example, causes non-blog articles to be pulled in. You need to filter by the blog section. 

{{ range first 3 (where .Site.RegularPages "Section" "blog") }}

or better

{{ range first 3 (where (where .Site.RegularPages.ByPublishDate "Section" "blog") ".Draft" "!=" true) }}
